// Server entry: pure schema.org builders + the Metadata factory. No React, so
// route handlers / sitemap.ts can import these without pulling in the renderer.
// The <JsonLd> and <HreflangLinks> components live at
// "@ingram-tech/nk-seo/components".
export {
	type AggregateOfferNode,
	type AggregateRatingInput,
	type AggregateRatingNode,
	article,
	type ArticleAuthor,
	type ArticleAuthorNode,
	type ArticleInput,
	type ArticleNode,
	type ArticleType,
	breadcrumbList,
	type BreadcrumbItem,
	type BreadcrumbListNode,
	type BreadcrumbPath,
	createSeo,
	type DataDownloadInput,
	type DataDownloadNode,
	dataset,
	type DatasetInput,
	type DatasetNode,
	definedTerm,
	type DefinedTermInput,
	type DefinedTermNode,
	definedTermSet,
	type DefinedTermSetInput,
	type DefinedTermSetNode,
	event,
	type EventInput,
	type EventLocationInput,
	type EventNode,
	faqPage,
	type FaqItem,
	type FaqPageNode,
	type GeoCoordinatesNode,
	type GeoInput,
	type ImageObjectNode,
	type JsonLdNode,
	type ListItemNode,
	localBusiness,
	type LocalBusinessInput,
	type LocalBusinessNode,
	type OfferInput,
	type OfferNode,
	organization,
	type OrganizationInput,
	type OrganizationNode,
	person,
	type PersonInput,
	type PersonNode,
	type PlaceNode,
	type PostalAddressInput,
	type PostalAddressNode,
	type QuestionNode,
	type Seo,
	type SeoConfig,
	softwareApplication,
	type SoftwareApplicationInput,
	type SoftwareApplicationNode,
	type VirtualLocationNode,
	website,
	type WebsiteInput,
	type WebsiteNode,
	type WithContext,
	type WithExtra,
} from "./schema.js";
export {
	createMetadata,
	type MetadataSiteConfig,
	ogImageMetadata,
	type OgImageMetadataInput,
	type PageMetadata,
	type PageMetadataInput,
	type RootMetadataInput,
} from "./metadata.js";
export {
	createRobots,
	createSitemap,
	type RobotsConfig,
	type SitemapConfig,
	type SitemapLanguages,
	type SitemapRoute,
} from "./routes.js";
export {
	hreflangAlternates,
	type HreflangAlternates,
	type HreflangConfig,
	type HreflangLink,
} from "./alternates.js";
